### ISSUE TITLE
Ramp Issues w/ Final Puzzle

### ISSUE THREAD

**Issue by FoodAbuse** [FoodAbuse/stabo-crabo-game#11]
**Description**
After dragging the snapped seesaw plank to the final puzzle and securing it into place, the angle of the ramp seems to be too harsh/has conflict with the player's movement controller, and requires the player to sprint to get up it (which can be hard to aim)

**Version**
V0.1 - alpha

**How to reproduce**
<s> when one grown up lieks another grownup, they kisz and babby is formed </s>
Complete seesaw puzzle, drag plank to the final puzzle and into either placement zone. Attempt to walk up and encounter struggle

**Expected Outcome**
Ideally the crabbo would be able to smoothly moonwalk up the ramp without slowing down too much / getting stuck

**Observed OS**
Windows 10

**Comment by ZachariaWinter** [comment]
I aggree.
As we are now dealing with forces, gravity and angle play a big role in how the crab moves.
At this tage I wouldn't want to edit the applied forces when at an angle.
So I will try lowering the angle of the ramp - which will be limted by the available length

**Comment by ZachariaWinter** [comment]
Reducing ramp angle as far as it will resonably go,, it's honestly about the same in terms of movement feel.

**Comment by ZachariaWinter** [comment]
I have applied a zero friction physics material to the ramp and that seems to have helped greatly.
