### ISSUE TITLE
Esky Man Holding a Whole Lotta Nothin!

### ISSUE THREAD

**Issue by FoodAbuse** [FoodAbuse/stabo-crabo-game#12]
**Description** 
After the esky man gets shanked for asking the time in London and drops his heavy load, he resumes his strenuous carry animation with nothing in his hands! Crickey!

(I am completely clueless with animation cues in Unity, I had a poke around but to no avail)

**Version**
V0.1 - alpha

**How to reproduce**
Shank da esky man, kick your feet up and watch the show

**Observed OS**
Windows 85

**Comment by ZachariaWinter** [comment]
For now, I ahve fixed this with a very specific bit of script.
Next semester I would like to create a function for chanigng NPC behaviour, and then link that in to the esky puzzle controller.
