### ISSUE TITLE
Quit button not functioning

### ISSUE THREAD

**Issue by FoodAbuse** [FoodAbuse/stabo-crabo-game#28]
For some reason in our latest build the quit button no longer works, too tired to figure it out currently so I'm putting it here in case it needs to be looked at before I get around to fully debugging and fixing it and also because I will otherwise completely forget

**Comment by ZachariaWinter** [comment]
During our prep for PGF, there were many hands working on the UI manager prefab.
this led to some button commands becoming disconnected.
I have reconnected it and also added the code to make it quit play mode if run in editor
