### ISSUE TITLE
An NPC in line still runs when stabbed

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#32]
Description
One of the NPCs at the front of the ice cream line in lv 2 still has the flee script attached, meaning when you stab them they run, leaving a gap. It's the second in line, behind the child.

Version
n/a

To Reproduce
n/a

Expected behavior
They shouldn't flee

Screenshots
n/a

Desktop System (please complete the following information):

    OS: Windows10

Additional context
n/a

**Comment by ZachariaWinter** [comment]
Found the problem NPC and set their fleetime to 0
They also were not a child of the waiting line parent, so I moved them.

Stabbed each NPC in the line in editor play mode to double check that none of them run.
