### ISSUE TITLE
Duplicating boards with weird behaviours

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#34]
**Description**
Grabbing the ungrabbable planks on the left jetty causes them to clone, be held at the exact angle and position they were left, and teleport to the crab whenever the grab button is clicked. This softlocks progression if you haven't already beat the level

**Version**
pgf build

**To replicate**

1. level 1
2. attempt to grab the two planks in the hollow to the left of the restaurant, the ones used as an example ramp
3. try to grab other things

**OS**
windows 10

**Notes**
n/a

**Comment by FoodAbuse** [comment]
**Patch Notes**
Interactable script was still on planks (although disabled, the grab function was still able to detect the scripts and read their values). Removing has rectified the issue

Going forwards, we will have to ensure that only the necessary objects have the _Interactable_ script on them
