### ISSUE TITLE
Camera moves in disorientating ways

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#35]
**Description**
In certain areas (especially at the jetty, or around the open umbrellas) the camera moves in a way that feels a bit too extreme for what is happening, sometimes zooming in and out at random or without warning.

**Version**
pgf build

**To replicate**

1. Any level, but specifically lv1
2. Move around in the aforementioned areas

**Notes**
It works more or less as expected around the building corners, but probably shouldn't activate around the jetty at all.

**Comment by ZachariaWinter** [comment]
Camera was previously avoiding 2 layers: structures and trees
I have created a new layer: Structures-Tall, and used it to differentiate between the low to ground jetty barrier, and the larger buildings.
The camera should no longer care about the jetty railing, the small blue bins, the park benches, ice cream truck, the boats on the right.

It should never have been actiout weird around the umbrellas, I believe it was reacting to the benches that the umbrellas were in the middle of.

If people ever want to change whether an object is reacted to by the camera, they can simply change if it is in structures vs structures-tall (even if in reality the object's geometry is not actually tall).
