### ISSUE TITLE
Ramp Physics Breaking

### ISSUE THREAD

**Issue by FoodAbuse** [FoodAbuse/stabo-crabo-game#40]
Ramp breaks after stabbing target and slides around scene

Does not happen every time.
Specific cause is unknown but solution is simple: need to get rid of interactable and rigid body on the plank ramp that is created.

**Comment by ZachariaWinter** [comment]
Upon further investigation the cause of the plank moving and is that it is still stabbable. The sliding physics is still unknown.
Also, for some reason the puzzle controller is spawning the plank twice in the same spot fairly consistently.
Altering the prefab fixes the first issue, so I will need to look further into the second...

**Comment by ZachariaWinter** [comment]
Found the issue. There was a second identical puzzle object that was renamed to one of the level 2 puzzle triggers.
But was really just a clone of the plank trigger. Don't know how it got there but either way it is delted, prefab has been updated. Tested the gameplay loop and it all works fine.
