### ISSUE TITLE
Shaders change between levels

### ISSUE THREAD

**Issue by ZachariaWinter** [FoodAbuse/stabo-crabo-game#44]
**Description**

When entering and then leaving a level using the menu systems, the changes to environment and shader colours remain, permanently altering the materials.

**Version**
n/a

**To Reproduce**
1. Start with any level scene, or start with menu and enter a level
2. Click esc to access menu, and click 'back to menu'
3. The menu scene will have altered colours, as will any level you now enter

**Expected behavior**
The colours revert to their set hues for each scene.

**Screenshots**
![image](https://github.com/FoodAbuse/stabo-crabo-game/assets/127712819/12b3e704-377c-477f-a70f-7bde7dcb6f5b)

**Desktop System (please complete the following information):**
- Windows 10

**Additional context**
n/a

**Comment by FoodAbuse** [comment]
Shader now no longer has individual control over lighting per material, instead runs on a global value. This is now set by the level loader, so whenever it loads a new scene it passes the scene name as a string to the shader controller script, which updates accordingly
